spring:
  main:
    web-application-type: none
    banner-mode: 'off'
    log-startup-info: false
logging:
  level:
    root: WARN
application:
  coindesk:
    api:
      baseEndpointUrl: https://api.coindesk.com/v1/bpi/
